language: elixir

elixir:
  - 1.5.3
  - 1.6.4
  - 1.7.1

addons:
  postgresql: '9.5'

services:
  - postgresql

before_script:
  - psql -c 'create database rihanna_db;' -U postgres -h localhost

script:
  - mix test
